steps:
  # Build imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend',
      './back'
    ]

  # Push imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend'
    ]

  # Deploy a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'cltiene-backend',
      '--image', 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--traffic', 'latest'
    ]

images:
  - 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend'

options:
  logging: CLOUD_LOGGING_ONLY