steps:
  # --- BACKEND ---
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend',
      './back'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'cltiene-backend',
      '--image', 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=desarrollo-investigaciones'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'services', 'update-traffic', 'cltiene-backend',
      '--to-latest', '--region', 'us-central1'
    ]

  # --- DASHBOARD (frontend) ---
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-dashboard',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-dashboard'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'cltiene-dashboard',
      '--image', 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-dashboard',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'services', 'update-traffic', 'cltiene-dashboard',
      '--to-latest', '--region', 'us-central1'
    ]

images:
  - 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-backend'
  - 'us-central1-docker.pkg.dev/desarrollo-investigaciones/backend-repo/cltiene-dashboard'

options:
  logging: CLOUD_LOGGING_ONLY
